// Examples
// import "./examples/abstraction";
// import "./examples/encapsulation";
// import "./examples/ocp";
// import "./examples/builder";
// import "./examples/factory";
// import "./examples/abstraction-factory";
// import "./examples/facade";
// import "./examples/bridge";
// import "./examples/composite";
// import "./examples/decorator";
// import "./examples/adapter";
// import "./examples/observable";
// import "./examples/iterator";
// import "./examples/strategy";
// import "./examples/template";
// import "./examples/command";
// import "./examples/state-design";
import "./examples/chain";

// Exercises
// import "./exercises/abstraction";
// import "./exercises/inheritance";
// import "./exercises/liskov";
// import "./exercises/isp";
// import "./exercises/singleton";
// import "./exercises/prototype";
// import "./exercises/builder";
// import "./exercises/factory";
// import "./exercises/abstraction-factory";
// import "./exercises/facade";
// import "./exercises/bridge";
// import "./exercises/composite";
// import "./exercises/decorator";
// import "./exercises/adapter";
// import "./exercises/observable";
// import "./exercises/iterator";
// import "./exercises/strategy";
// import "./exercises/template";
// import "./exercises/command";
// import "./exercises/state-design";
